import {
  Home,
  Package,
  User,
  List,
  ToolCaseIcon,
  BoxIcon,
  Database,
} from "lucide-react";

export const navigationItems = [
  {
    name: "Dashboard",
    href: "/",
    icon: Home,
  },
  {
    name: "Employee",
    href: "/users",
    icon: User,
  },
  {
    name: "Master Data",
    icon: Database,
    children: [
      { name: "Telepon", href: "/master-data/telepon" },
      { name: "Synology", href: "/master-data/synology" },
      { name: "NVR CCTV", href: "/master-data/nvr-cctv" },
      { name: "Camera CCTV", href: "/master-data/camera-cctv" },
      { name: "Scanner", href: "/master-data/scanner" },
      { name: "Fingerprint", href: "/master-data/fingerprint" },
      { name: "Switch", href: "/master-data/switch" },
      { name: "Radio", href: "/master-data/radio" },
      { name: "UPS", href: "/master-data/ups" },
      { name: "Router", href: "/master-data/router" },
      { name: "Komputer", href: "/master-data/komputer" },
      { name: "Access Point", href: "/master-data/access-point" },
      { name: "Printer", href: "/master-data/printer" },
      { name: "Laptop", href: "/master-data/laptop" },
    ],
  },
  {
    name: "Manufaktur",
    icon: BoxIcon,
    children: [
      { name: "Telepon", href: "/manufaktur/telepon" },
      { name: "Synology", href: "/manufaktur/synology" },
      { name: "NVR CCTV", href: "/manufaktur/nvr-cctv" },
      { name: "Camera CCTV", href: "/manufaktur/camera-cctv" },
      { name: "Scanner", href: "/manufaktur/scanner" },
      { name: "Fingerprint", href: "/manufaktur/fingerprint" },
      { name: "Switch", href: "/manufaktur/switch" },
      { name: "Radio", href: "/manufaktur/radio" },
      { name: "UPS", href: "/manufaktur/ups" },
      { name: "Router", href: "/manufaktur/router" },
      { name: "Komputer", href: "/manufaktur/komputer" },
      { name: "Access Point", href: "/manufaktur/access-point" },
      { name: "Printer", href: "/manufaktur/printer" },
      { name: "Laptop", href: "/manufaktur/laptop" },
    ],
  },
  {
    name: "Items",
    icon: Package,
    children: [
      { name: "Telepon", href: "/items/telepon" },
      { name: "Synology", href: "/items/synology" },
      { name: "NVR CCTV", href: "/items/nvr-cctv" },
      { name: "Camera CCTV", href: "/items/camera-cctv" },
      { name: "Scanner", href: "/items/scanner" },
      { name: "Fingerprint", href: "/items/fingerprint" },
      { name: "Switch", href: "/items/switch" },
      { name: "Radio", href: "/items/radio" },
      { name: "UPS", href: "/items/ups" },
      { name: "Router", href: "/items/router" },
      { name: "Komputer", href: "/items/komputer" },
      { name: "Access Point", href: "/items/access-point" },
      { name: "Printer", href: "/items/printer" },
      { name: "Laptop", href: "/items/laptop" },
    ],
  },
  {
    name: "View Device",
    icon: List,
    children: [
      { name: "Telepon", href: "/view-devices/telepon" },
      { name: "Synology", href: "/view-devices/synology" },
      { name: "NVR CCTV", href: "/view-devices/nvr-cctv" },
      { name: "Camera CCTV", href: "/view-devices/camera-cctv" },
      { name: "Scanner", href: "/view-devices/scanner" },
      { name: "Fingerprint", href: "/view-devices/fingerprint" },
      { name: "Switch", href: "/view-devices/switch" },
      { name: "Radio", href: "/view-devices/radio" },
      { name: "UPS", href: "/view-devices/ups" },
      { name: "Router", href: "/view-devices/router" },
      { name: "Komputer", href: "/view-devices/komputer" },
      { name: "Access Point", href: "/view-devices/access-point" },
      { name: "Printer", href: "/view-devices/printer" },
      { name: "Laptop", href: "/view-devices/laptop" },
    ],
  },
  {
    name: "Service Record",
    href: "/service-record",
    icon: ToolCaseIcon,
  },
];
