// This file defines custom TypeScript types for the application.
// It complements the types generated by Prisma for client-side use.

import { DefaultSession } from "next-auth";

// --- CORE MODELS ---

export interface User {
  id: number;
  namaLengkap: string;
  email: string | null;
  departemen: string | null;
  jabatan: string | null;
  lokasiKantor: string | null;
  isActive: boolean;
  role?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface AssetCategory {
  id: number;
  nama: string;
  slug: string;
}

// --- NEW INTERFACE FOR OFFICE ACCOUNT ---
export interface OfficeAccount {
  id: number;
  email: string;
  password: string;
  licenseExpiry: Date | null;
  isActive: boolean;
  assetId: number;
}

export interface Asset {
  id: number;
  namaAsset: string;
  categoryId: number;
  nomorSeri: string;
  tanggalPembelian: Date | null;
  tanggalGaransi: Date | null;
  statusAsset: string;
  createdAt: Date;
  updatedAt: Date;
  // Menambahkan relasi yang mungkin di-include
  category: AssetCategory;
  laptopSpecs?: LaptopSpecs;
  intelNucSpecs?: IntelNucSpecs;
  printerSpecs?: PrinterSpecs;
  cctvSpecs?: CctvSpecs;
  officeAccount?: OfficeAccount; // <-- TAMBAHKAN INI
}

export interface AssetAssignment {
  id: number;
  assetId: number;
  userId: number;
  catatan: string | null;
  createdAt: Date;
  updatedAt: Date;
  nomorAsset: string;
  // Menambahkan relasi yang mungkin di-include
  asset?: Asset;
  user?: User;
  computerMaintenances?: ComputerMaintenance[];
}


export interface AssetAssignmentPrinter {
  id: number;
  assetId: number;
  userId: number;
  catatan: string | null;
  createdAt: Date;
  updatedAt: Date;
  nomorAsset: string;
  // Menambahkan relasi yang mungkin di-include
  asset?: {
    namaAsset: Asset["namaAsset"];
    categoryId: Asset["categoryId"];
    nomorSeri: Asset["nomorSeri"];
    printerSpecs:{
      brandOption: {
        value: string;
      }
    }
  };
}

export interface ServiceRecord {
  id: number;
  ticketHelpdesk: string;
  repairType: string;
  cost: number;
  remarks: string | null;
  createdAt: Date;
  updatedAt: Date;
  assetAssignmentId: number;
  // Menambahkan relasi yang mungkin di-include
  assetAssignment?: AssetAssignment;
}

export interface AssetAssignmentWithDetails extends AssetAssignment {
  asset: Asset;
  user: User;
}

export interface ServiceRecordWithDetails extends ServiceRecord {
  assetAssignment: AssetAssignmentWithDetails;
}

// --- MASTER DATA / LOOKUP TYPES ---

// A generic interface for simple master data options that just have an ID and a value.
export interface MasterDataOption {
  id: number;
  value: string;
}

// Specific types for laptop options
export type LaptopRamOption = MasterDataOption;
export type LaptopProcessorOption = MasterDataOption;
export type LaptopStorageTypeOption = MasterDataOption;
export type LaptopOsOption = MasterDataOption;
export type LaptopPowerOption = MasterDataOption;
export type LaptopMicrosoftOfficeOption = MasterDataOption;
export type LaptopColorOption = MasterDataOption;
export type LaptopBrandOption = MasterDataOption;
export type LaptopTypeOption = MasterDataOption;
export type LaptopGraphicOption = MasterDataOption;
export type LaptopVgaOption = MasterDataOption;
export type LaptopLicenseOption = MasterDataOption;

// Specific types for printer options
export type PrinterTypeOption = MasterDataOption;
export type PrinterBrandOption = MasterDataOption;
export type PrinterModelOption = MasterDataOption;
export type CallOutgoingOption = MasterDataOption;
export type CoGroupOption = MasterDataOption;

// Specific types for CCTV options
export type CctvBrandOption = MasterDataOption;
export type CctvModelOption = MasterDataOption;
export type CctvDeviceTypeOption = MasterDataOption;
export interface CctvChannelCameraOption {
  id: number;
  lokasi: string;
  sbu: string;
}

// --- SPECIFICATION TYPES ---

// Base interface for all specification models
export interface AssetSpecs {
  assetId: number;
  macWlan: string | null;
  macLan: string | null;
}

// Spesifikasi untuk Laptop
export interface LaptopSpecs extends AssetSpecs {
  // Properti relasi
  processorOption?: LaptopProcessorOption;
  ramOption?: LaptopRamOption;
  storageTypeOption?: LaptopStorageTypeOption;
  licenseOption?: LaptopLicenseOption;
  osOption?: LaptopOsOption;
  powerOption?: LaptopPowerOption;
  microsoftOfficeOption?: LaptopMicrosoftOfficeOption;
  colorOption?: LaptopColorOption;
  graphicOption?: LaptopGraphicOption;
  vgaOption?: LaptopVgaOption;
  brandOption?: LaptopBrandOption;
  typeOption?: LaptopTypeOption;
}

// Spesifikasi untuk Intel NUC
export interface IntelNucSpecs extends AssetSpecs {
  // Properti relasi
  processorOption?: LaptopProcessorOption;
  ramOption?: LaptopRamOption;
  storageTypeOption?: LaptopStorageTypeOption;
  licenseOption?: LaptopLicenseOption;
  osOption?: LaptopOsOption;
  powerOption?: LaptopPowerOption;
  microsoftOfficeOption?: LaptopMicrosoftOfficeOption;
  colorOption?: LaptopColorOption;
  graphicOption?: LaptopGraphicOption;
  vgaOption?: LaptopVgaOption;
  brandOption?: LaptopBrandOption;
  typeOption?: LaptopTypeOption;
}

// Spesifikasi untuk Printer
export interface PrinterSpecs {
  assetId: number;
  typeOptionId?: number | null  ;
  brandOptionId?: number | null  ;
  modelOptionId?: number | null ;
  // Properti relasi
  typeOption?: PrinterTypeOption;
  brandOption?: PrinterBrandOption;
  modelOption?: PrinterModelOption;
}

// Spesifikasi untuk CCTV
export interface CctvSpecs {
  assetId: number;
  sbu: string; // Assuming Sbu is an enum/string
  nameSite: string;
  viewCamera: string;
  systemVersion: string | null;
  power: string | null;
  ipAddress: string;
  macAddress: string | null;
  username: string | null;
  password: string | null;
  brandId: number | null;
  modelId: number | null;
  deviceTypeId: number | null;
  channelCameraId: number | null;
  // Relasi
  brand?: CctvBrandOption;
  model?: CctvModelOption;
  deviceType?: CctvDeviceTypeOption;
  channelCamera?: CctvChannelCameraOption;
}

export interface PrinterRepetitiveMaintenance {
  id: number;
  reportDate: Date;
  assetDetails: string | null;
  totalPages: number | null;
  catatan: string | null;
  blackCount: number | null;
  yellowCount: number | null;
  magentaCount: number | null;
  cyanCount: number | null;
  remarks: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProblemSequence {
  id: number;
  ticketNumber: string;
  sbu: string;
  ispId: number;
  pic: string;
  dateDown: Date;
  dateDoneUp: Date;
  issue: string;
  trouble: string;
  solved: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProblemSequenceWithIsp extends ProblemSequence {
  isp: {
    id: number;
    isp: string;
    hpNoc: string;
    picNoc: string;
  };
}

export interface BilingRecord {
  id: number;
  callDate: Date;
  userId: number;
  extension: number;
  dial: string;
  duration: string;
  trunk: number;
  pstn: number;
  cost: number | string | { toString: () => string };
  createdAt: Date;
  updatedAt: Date;
}

export interface BilingRecordWithUser extends BilingRecord {
  user: User;
}

export interface PhoneAccount {
  id: number;
  userId: number;
  extension: number;
  account: number;
  codeDial: string;
  deposit: string;
  callOutgoingId: number;
  coGroupId: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface PhoneAccountWithDetails extends PhoneAccount {
  user: User;
  callOutgoingOption: CallOutgoingOption;
  coGroupOption: CoGroupOption;
}

export interface ComputerMaintenance {
  id: number;
  periode: Date;
  assetAssignmentId: number;
  connection: "WIFI" | "ETHERNET";
  storageSystemC: string | null;
  storageDataD: string | null;
  health: string | null;
  cpuFan: string | null;
  temperature: number | null;
  windowsUpdate: Date | null;
  remarks: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComputerMaintenanceWithDetails extends ComputerMaintenance {
  assetAssignment: AssetAssignmentWithDetails;
}
