// This file defines custom TypeScript types for the application.
// It complements the types generated by Prisma for client-side use.

import { DefaultSession } from "next-auth";

// --- CORE MODELS ---

export interface User {
  id: number;
  namaLengkap: string;
  email: string | null;
  departemen: string | null;
  jabatan: string | null;
  lokasiKantor: string | null;
  isActive: boolean;
  role?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface AssetCategory {
  id: number;
  nama: string;
  slug: string;
}

// --- NEW INTERFACE FOR OFFICE ACCOUNT ---
export interface OfficeAccount {
  id: number;
  email: string;
  password: string;
  licenseExpiry: Date | null;
  isActive: boolean;
  assetId: number;
}

export interface Asset {
  id: number;
  namaAsset: string;
  categoryId: number;
  nomorSeri: string;
  tanggalPembelian: Date | null;
  tanggalGaransi: Date | null;
  statusAsset: string;
  createdAt: Date;
  updatedAt: Date;
  lokasiFisik?: string | null;
  // Menambahkan relasi yang mungkin di-include
  category: AssetCategory;
  laptopSpecs?: LaptopSpecs;
  intelNucSpecs?: IntelNucSpecs;
  pcSpecs?: PcSpecs;
  printerSpecs?: PrinterSpecs;
  cctvSpecs?: CctvSpecs;
  officeAccount?: OfficeAccount; // <-- TAMBAHKAN INI
  assignmentHistories?: AssetAssignmentHistory[];
}

export interface AssetAssignment {
  id: number;
  assetId: number;
  userId: number;
  catatan: string | null;
  createdAt: Date;
  updatedAt: Date;
  nomorAsset: string;
  // Menambahkan relasi yang mungkin di-include
  asset?: Asset;
  user?: User;
  computerMaintenances?: ComputerMaintenance[];
}


export interface AssetAssignmentPrinter {
  id: number;
  assetId: number;
  userId: number;
  catatan: string | null;
  createdAt: Date;
  updatedAt: Date;
  nomorAsset: string;
  // Menambahkan relasi yang mungkin di-include
  asset?: {
    namaAsset: Asset["namaAsset"];
    categoryId: Asset["categoryId"];
    nomorSeri: Asset["nomorSeri"];
    printerSpecs:{
      brandOption: {
        value: string;
      }
    }
  };
}

export interface ServiceRecord {
  id: number;
  ticketHelpdesk: string;
  repairType: string;
  cost: number;
  remarks: string | null;
  createdAt: Date;
  updatedAt: Date;
  assetAssignmentId: number;
  // Menambahkan relasi yang mungkin di-include
  assetAssignment?: AssetAssignment;
}

export interface AssetAssignmentWithDetails extends AssetAssignment {
  asset: Asset;
  user: User;
}

export interface AssetAssignmentHistory {
  id: number;
  assetId: number;
  userId: number | null;
  nomorAsset: string | null;
  catatan: string | null;
  startedAt: Date;
  endedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  asset?: Asset;
  user?: User | null;
}

export type TrackerDeviceFamily = "LAPTOP" | "INTEL_NUC" | "PC";

export interface TrackedAsset extends Asset {
  assignmentHistories: AssetAssignmentHistory[];
}

export interface ServiceRecordWithDetails extends ServiceRecord {
  assetAssignment: AssetAssignmentWithDetails;
}

// --- MASTER DATA / LOOKUP TYPES ---

// A generic interface for simple master data options that just have an ID and a value.
export interface MasterDataOption {
  id: number;
  value: string;
}

// Specific types for laptop options
export type LaptopRamOption = MasterDataOption;
export type LaptopProcessorOption = MasterDataOption;
export type LaptopStorageTypeOption = MasterDataOption;
export type LaptopOsOption = MasterDataOption;
export type LaptopPowerOption = MasterDataOption;
export type LaptopMicrosoftOfficeOption = MasterDataOption;
export type LaptopColorOption = MasterDataOption;
export type LaptopBrandOption = MasterDataOption;
export type LaptopTypeOption = MasterDataOption;
export type LaptopGraphicOption = MasterDataOption;
export type LaptopVgaOption = MasterDataOption;
export type LaptopLicenseOption = MasterDataOption;
export type PcMonitorOption = MasterDataOption;
export type PcMotherboardOption = MasterDataOption;
export type PcUpsOption = MasterDataOption;

// Specific types for printer options
export type PrinterTypeOption = MasterDataOption;
export type PrinterBrandOption = MasterDataOption;
export type PrinterModelOption = MasterDataOption;
export interface CallOutgoingOption {
  id: number;
  value: number;
  line: number;
  company: string;
}
export interface TrunkOption {
  id: number;
  nomorLine: number;
  company: string;
  extension: number;
}
export interface PstnOption {
  id: number;
  pstnCode: number;
  pstnName: string;
}

// Specific types for CCTV options
export type CctvBrandOption = MasterDataOption;
export type CctvModelOption = MasterDataOption;
export type CctvDeviceTypeOption = MasterDataOption;
export interface CctvChannelCameraOption {
  id: number;
  lokasi: string;
  sbu: string;
}

// --- SPECIFICATION TYPES ---

// Base interface for all specification models
export interface AssetSpecs {
  assetId: number;
  macWlan: string | null;
  macLan: string | null;
}

// Spesifikasi untuk Laptop
export interface LaptopSpecs extends AssetSpecs {
  licenseKey?: string | null;
  // Properti relasi
  processorOption?: LaptopProcessorOption;
  ramOption?: LaptopRamOption;
  storageTypeOption?: LaptopStorageTypeOption;
  licenseOption?: LaptopLicenseOption;
  osOption?: LaptopOsOption;
  powerOption?: LaptopPowerOption;
  microsoftOfficeOption?: LaptopMicrosoftOfficeOption;
  colorOption?: LaptopColorOption;
  graphicOption?: LaptopGraphicOption;
  vgaOption?: LaptopVgaOption;
  brandOption?: LaptopBrandOption;
  typeOption?: LaptopTypeOption;
}

// Spesifikasi untuk Intel NUC
export interface IntelNucSpecs extends AssetSpecs {
  licenseKey?: string | null;
  // Properti relasi
  processorOption?: LaptopProcessorOption;
  ramOption?: LaptopRamOption;
  storageTypeOption?: LaptopStorageTypeOption;
  licenseOption?: LaptopLicenseOption;
  osOption?: LaptopOsOption;
  powerOption?: LaptopPowerOption;
  microsoftOfficeOption?: LaptopMicrosoftOfficeOption;
  colorOption?: LaptopColorOption;
  graphicOption?: LaptopGraphicOption;
  vgaOption?: LaptopVgaOption;
  brandOption?: LaptopBrandOption;
  typeOption?: LaptopTypeOption;
}

export interface PcSpecs {
  assetId: number;
  processorOptionId?: number | null;
  ramOptionId?: number | null;
  storageTypeOptionId?: number | null;
  licenseOptionId?: number | null;
  licenseKey?: string | null;
  osOptionId?: number | null;
  powerOptionId?: number | null;
  microsoftOfficeOptionId?: number | null;
  colorOptionId?: number | null;
  graphicOptionId?: number | null;
  monitorOptionId?: number | null;
  motherboardOptionId?: number | null;
  upsOptionId?: number | null;
  casing?: string | null;
  macLan?: string | null;
  processorOption?: LaptopProcessorOption;
  ramOption?: LaptopRamOption;
  storageTypeOption?: LaptopStorageTypeOption;
  licenseOption?: LaptopLicenseOption;
  osOption?: LaptopOsOption;
  powerOption?: LaptopPowerOption;
  microsoftOfficeOption?: LaptopMicrosoftOfficeOption;
  colorOption?: LaptopColorOption;
  graphicOption?: LaptopGraphicOption;
  monitorOption?: PcMonitorOption;
  motherboardOption?: PcMotherboardOption;
  upsOption?: PcUpsOption;
}

// Spesifikasi untuk Printer
export interface PrinterSpecs {
  assetId: number;
  typeOptionId?: number | null  ;
  brandOptionId?: number | null  ;
  modelOptionId?: number | null ;
  // Properti relasi
  typeOption?: PrinterTypeOption;
  brandOption?: PrinterBrandOption;
  modelOption?: PrinterModelOption;
}

// Spesifikasi untuk CCTV
export interface CctvSpecs {
  assetId: number;
  sbu: string; // Assuming Sbu is an enum/string
  nameSite: string;
  viewCamera: string;
  systemVersion: string | null;
  power: string | null;
  ipAddress: string;
  macAddress: string | null;
  username: string | null;
  password: string | null;
  brandId: number | null;
  modelId: number | null;
  deviceTypeId: number | null;
  channelCameraId: number | null;
  // Relasi
  brand?: CctvBrandOption;
  model?: CctvModelOption;
  deviceType?: CctvDeviceTypeOption;
  channelCamera?: CctvChannelCameraOption;
}

export interface PrinterRepetitiveMaintenance {
  id: number;
  reportDate: Date;
  assetDetails: string | null;
  totalPages: number | null;
  catatan: string | null;
  blackCount: number | null;
  yellowCount: number | null;
  magentaCount: number | null;
  cyanCount: number | null;
  remarks: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProblemSequence {
  id: number;
  ticketNumber: string;
  sbu: string;
  ispId: number;
  pic: string;
  dateDown: Date;
  dateDoneUp: Date;
  issue: string;
  trouble: string;
  solved: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProblemSequenceWithIsp extends ProblemSequence {
  isp: {
    id: number;
    isp: string;
    hpNoc: string;
    picNoc: string;
  };
}

export type SparepartDeviceFamily = "LAPTOP" | "INTEL_NUC" | "PC";
export type SparepartPartType =
  | "BRAND"
  | "TYPE"
  | "PROCESSOR"
  | "RAM"
  | "STORAGE"
  | "OS"
  | "POWER"
  | "LICENSE"
  | "MICROSOFT_OFFICE"
  | "COLOR"
  | "GRAPHIC"
  | "VGA"
  | "MONITOR"
  | "MOTHERBOARD"
  | "UPS";
export type SparepartMovementType = "MASUK" | "PAKAI" | "ADJUSTMENT";
export type SparepartAdjustmentDirection = "INCREASE" | "DECREASE";

export interface SparepartMovement {
  id: number;
  deviceFamily: SparepartDeviceFamily;
  partType: SparepartPartType;
  sourceOptionId: number;
  sourceOptionValue: string;
  movementType: SparepartMovementType;
  adjustmentDirection?: SparepartAdjustmentDirection | null;
  quantity: number;
  movedAt: Date;
  userId?: number | null;
  stockOwnerUserId?: number | null;
  sourceAssignmentId?: number | null;
  notes?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface SparepartSourceAssignment {
  id: number;
  nomorAsset: string;
  userId: number;
  assetId: number;
  user?: Pick<User, "id" | "namaLengkap"> | null;
  asset?: Pick<Asset, "id" | "namaAsset" | "nomorSeri"> | null;
}

export interface SparepartMovementWithUser extends SparepartMovement {
  user?: User | null;
  stockOwner?: Pick<User, "id" | "namaLengkap"> | null;
  sourceAssignment?: SparepartSourceAssignment | null;
}

export interface SparepartSourceAssignmentOption {
  id: number;
  userId: number;
  userName: string;
  assetId: number;
  assetName: string;
  serialNumber: string;
  nomorAsset: string;
  label: string;
}

export interface BilingRecord {
  id: number;
  callDate: Date;
  userId: number;
  extension: number;
  dial: string;
  duration: string;
  trunk: number;
  pstn: number;
  cost: number | string | { toString: () => string };
  createdAt: Date;
  updatedAt: Date;
}

export interface BilingRecordWithUser extends BilingRecord {
  user: User;
}

export interface PhoneAccount {
  id: number;
  userId: number;
  extension: number;
  account: number;
  codeDial: string;
  deposit: string | number | { toString: () => string };
  callOutgoingId: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface PhoneAccountWithDetails extends PhoneAccount {
  user: User;
  callOutgoingOption: CallOutgoingOption;
}

export interface ComputerMaintenance {
  id: number;
  periode: Date;
  assetAssignmentId: number;
  connection: "WIFI" | "ETHERNET";
  storageSystemC: string | null;
  storageDataD: string | null;
  health: string | null;
  cpuFan: string | null;
  temperature: number | null;
  windowsUpdate: Date | null;
  remarks: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface ComputerMaintenanceWithDetails extends ComputerMaintenance {
  assetAssignment: AssetAssignmentWithDetails;
}
