services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: datek-mis
    ports:
      - "3001:3001"
      - "5555:5555" 

    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
